name: Zip emojis
permissions:
  contents: write

on: [push]
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Zip
        run: zip -r emojis.zip . -x ".github/*" ".git/*" README.md ".gitignore"
        shell: bash

      - name: Upload release
        run: gh release create `git log -n 1 --pretty=format:"%h"` emojis.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash